<?php

/**
 * @file
 * Primary module hooks for webform verify user module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
* Implements hook_mail().
*/
function webform_verify_user_mail($key, &$message, $params) {

  switch ($key) {
    case 'otp_validation':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'] = [$params['body']];
      break;
  }

  $site_mail = \Drupal::config('system.site')->get('mail');
  $message['headers']['MIME-Version'] = '1.0';
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  $message['headers']['Return-Path'] = $site_mail;
}
